### ISSUE TITLE
Telstra

### ISSUE THREAD

**Issue by 161134050** [dennis87532/ToyRobotSimulator#1]
Is this for the Telstra thing? They declined my C++ approach and didn't give me any feedback!

**Comment by dennis87532** [comment]
This was not for Telstra. It originated with ANZ https://joneaves.wordpress.com/2014/07/21/toy-robot-coding-test/ and has made its way around the world - I have seen it in Europe as well as here in NZ. FYI this solution was also rejected with very little feedback so I opened https://codereview.stackexchange.com/questions/230520/c-toy-robot-simulator to get feedback from the community. You might be able to do the same if you want feedback. I don't know c++ so I won't be able to do it myself though.
